# Generated by Django 4.1.6 on 2024-02-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('ovino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovino',
            name='tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tag.tag'),
        ),
    ]
